### ISSUE TITLE
Hi just wondering if its possible to change the node, id like to use Quiknode and where to enter these values

### ISSUE THREAD

**Issue by furiouseli** [T0Th3M00n/pancakeswap-sniping-bot#2]

**Comment by T0Th3M00n** [comment]
Is quicknode a UniSwap fork / clone? If so, it should be possible. If not, you would need to analyze how Quiknode works and create a custom bot. :)

**Comment by furiouseli** [comment]
from my understanding node is nodes = Functions
Stores the full blockchain history on disk and can answer the data request from the network.
Receives and validates the new blocks and transactions.
Verifies the states of every accounts.
A bot called Trade butler uses a custom node for the fastest snipe, this is where the bot will read liquidity from.
more info on https://docs.binance.org/smart-chain/developer/fullnode.html
And quiknode is a private node for bsc https://www.quiknode.io/. 
Was just wondering if i can somehow use your bot to use a private node so its faster
