### ISSUE TITLE
SyntaxError: 

### ISSUE THREAD

**Issue by Ghonghito** [T0Th3M00n/pancakeswap-sniping-bot#6]
Hello, when I typing node bot.js its shows me this error: 

import ethers from 'ethers';
^^^^^^

SyntaxError: Cannot use import statement outside a module

how can i fix that?

**Comment by T0Th3M00n** [comment]
This problem is because of your package.json file most likely. In the readme there are more details, but TLDR; I'd imagine you need "type": "module", on line 6 of your package.json file.

**Comment by Ghonghito** [comment]
Thanks
